// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/remote/proto/remote_execution.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	InputJson     string                 `protobuf:"bytes,2,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"` // JSON serialized AgentInput
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_pkg_remote_proto_remote_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_remote_proto_remote_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_remote_proto_remote_execution_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *ExecuteRequest) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

func (x *ExecuteRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExecuteRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecuteRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputJson    string                 `protobuf:"bytes,1,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"` // JSON serialized AgentOutput
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DurationMs    int64                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_pkg_remote_proto_remote_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_remote_proto_remote_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_remote_proto_remote_execution_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExecuteResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecuteResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_pkg_remote_proto_remote_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_remote_proto_remote_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_pkg_remote_proto_remote_execution_proto_rawDescGZIP(), []int{2}
}

func (x *HealthCheckRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_pkg_remote_proto_remote_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_remote_proto_remote_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_pkg_remote_proto_remote_execution_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_pkg_remote_proto_remote_execution_proto protoreflect.FileDescriptor

const file_pkg_remote_proto_remote_execution_proto_rawDesc = "" +
	"\n" +
	"'pkg/remote/proto/remote_execution.proto\x12\x06remote\"\x85\x02\n" +
	"\x0eExecuteRequest\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x1d\n" +
	"\n" +
	"input_json\x18\x02 \x01(\tR\tinputJson\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12@\n" +
	"\bmetadata\x18\x05 \x03(\v2$.remote.ExecuteRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x01\n" +
	"\x0fExecuteResponse\x12\x1f\n" +
	"\voutput_json\x18\x01 \x01(\tR\n" +
	"outputJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\"-\n" +
	"\x12HealthCheckRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"f\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp2\x9c\x01\n" +
	"\x16RemoteExecutionService\x12:\n" +
	"\aExecute\x12\x16.remote.ExecuteRequest\x1a\x17.remote.ExecuteResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.remote.HealthCheckRequest\x1a\x1b.remote.HealthCheckResponseB)Z'github.com/seyi/dagens/pkg/remote/protob\x06proto3"

var (
	file_pkg_remote_proto_remote_execution_proto_rawDescOnce sync.Once
	file_pkg_remote_proto_remote_execution_proto_rawDescData []byte
)

func file_pkg_remote_proto_remote_execution_proto_rawDescGZIP() []byte {
	file_pkg_remote_proto_remote_execution_proto_rawDescOnce.Do(func() {
		file_pkg_remote_proto_remote_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_remote_proto_remote_execution_proto_rawDesc), len(file_pkg_remote_proto_remote_execution_proto_rawDesc)))
	})
	return file_pkg_remote_proto_remote_execution_proto_rawDescData
}

var file_pkg_remote_proto_remote_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_remote_proto_remote_execution_proto_goTypes = []any{
	(*ExecuteRequest)(nil),      // 0: remote.ExecuteRequest
	(*ExecuteResponse)(nil),     // 1: remote.ExecuteResponse
	(*HealthCheckRequest)(nil),  // 2: remote.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 3: remote.HealthCheckResponse
	nil,                         // 4: remote.ExecuteRequest.MetadataEntry
}
var file_pkg_remote_proto_remote_execution_proto_depIdxs = []int32{
	4, // 0: remote.ExecuteRequest.metadata:type_name -> remote.ExecuteRequest.MetadataEntry
	0, // 1: remote.RemoteExecutionService.Execute:input_type -> remote.ExecuteRequest
	2, // 2: remote.RemoteExecutionService.HealthCheck:input_type -> remote.HealthCheckRequest
	1, // 3: remote.RemoteExecutionService.Execute:output_type -> remote.ExecuteResponse
	3, // 4: remote.RemoteExecutionService.HealthCheck:output_type -> remote.HealthCheckResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_remote_proto_remote_execution_proto_init() }
func file_pkg_remote_proto_remote_execution_proto_init() {
	if File_pkg_remote_proto_remote_execution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_remote_proto_remote_execution_proto_rawDesc), len(file_pkg_remote_proto_remote_execution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_remote_proto_remote_execution_proto_goTypes,
		DependencyIndexes: file_pkg_remote_proto_remote_execution_proto_depIdxs,
		MessageInfos:      file_pkg_remote_proto_remote_execution_proto_msgTypes,
	}.Build()
	File_pkg_remote_proto_remote_execution_proto = out.File
	file_pkg_remote_proto_remote_execution_proto_goTypes = nil
	file_pkg_remote_proto_remote_execution_proto_depIdxs = nil
}
